name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_GMAPS: ${{ secrets.NEXT_PUBLIC_GMAPS }}
        run: |
          npm install
          npm run stitchjson
          npm run build
          npm run export
          npm run deploy
